### ISSUE TITLE
Rmd adjustments

### ISSUE THREAD

**Issue by multidis** [gbolarhan/Visualization-In-R#1]
You may want to remove the `setwd` call
https://github.com/gbolarhan/Visualization-In-R/blob/main/A2Assignment.Rmd#L31

Also consider removing `install.packages`-calls from the R chunk - typically it is not the best practice to keep rerunning them every time the app is launched.

**Comment by gbolarhan** [comment]
@multidis Thank you for the feedback. Incorporating this in the next update.
